{
 "title": "Discount Club",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Requests Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (http_path)(capybelga_requests_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Plans",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(capybelga_active_clubs_ratio)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Discount Club Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(capybelga_new_plan_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Club Plan by Type",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (club_name) (capybelga_new_plan_count_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}